def desenhar_boneco(erros):
    if erros == 0:
        print("  ____")
        print(" |    |")
        print(" |")
        print(" |")
        print(" |")
        print(" |__________")
        print(" ")
    elif erros == 1:
        print("  ____")
        print(" |    |")
        print(" |    O")
        print(" |")
        print(" |")
        print(" |__________")
        print(" ")
    elif erros == 2:
        print("  ____")
        print(" |    |")
        print(" |    O")
        print(" |    |")
        print(" |")
        print(" |__________")
        print(" ")
    elif erros == 3:
        print("  ____")
        print(" |    |")
        print(" |    O")
        print(" |   /|")
        print(" |")
        print(" |__________")
        print(" ")
    elif erros == 4:
        print("  ____")
        print(" |    |")
        print(" |    O")
        print(" |   /|\\")
        print(" |")
        print(" |__________")
        print(" ")
    elif erros == 5:
        print("  ____")
        print(" |    |")
        print(" |    O")
        print(" |   /|\\")
        print(" |   / ")
        print(" |__________")
        print(" ")
    elif erros == 6:
        print("  ____")
        print(" |    |")
        print(" |    O")
        print(" |   /|\\")
        print(" |   / \\")
        print(" |__________")
        print(" ")


lista = [ "python","javascript", "aplicativos", "mobile", "usuario","servidor", "cafezinho"]